runtime: nodejs20
service: default
handlers:
  # Serve the main index.html at the root URL
  - url: /
    static_files: build/index.html
    upload: build/index.html
    secure: always
    redirect_http_response_code: 301

  # Serve all static files from the build directory
  - url: /(.*)
    static_files: build/\1
    upload: build/(.*)
