export const groups = [
	{ code: 2, description: "AGRUPACION PRUEBA" },
	{ code: 19, description: "VARIOS (LUBRICANTES)" },
	{ code: 331, description: "BALDWIN" },
	{ code: 41, description: "COSMETICA" },
	{ code: 48, description: "EAM" },
	{ code: 1, description: "FRAM" },
	{ code: 17, description: "HS" },
	{ code: 21, description: "JAPAN PARTS" },
	{ code: 29, description: "KARBON" },
	{ code: 14, description: "LOCX" },
	{ code: 15, description: "MAHLE" },
	{ code: 9, description: "MANN" },
	{ code: 332, description: "Marca" },
	{ code: 38, description: "MARENO" },
	{ code: 40, description: "MERCADO LIBRE" },
	{ code: 18, description: "MOLYKOTE" },
	{ code: 12, description: "MOTUL" },
	{ code: 46, description: "MOTUL OFERTAS" },
	{ code: 23, description: "OFERTAS FRAM" },
	{ code: 16, description: "OFERTAS KITS" },
	{ code: 25, description: "OFERTAS MENSUALES" },
	{ code: 32, description: "Originales FIAT" },
	{ code: 35, description: "Originales FORD" },
	{ code: 34, description: "Originales GM" },
	{ code: 316, description: "PETRONAS" },
	{ code: 3, description: "VALVOLINE" },
];

export const groups_prod = [
	{ code: 28, description: "AGRUPACION PRUEBA" },
	{ code: 48, description: "EAM" },
	{ code: 1, description: "FRAM" },
	{ code: 29, description: "KARBON" },
	{ code: 14, description: "LOCX" },
	{ code: 15, description: "MAHLE" },
	{ code: 9, description: "MANN" },
	{ code: 12, description: "MOTUL" },
	{ code: 32, description: "ORIGINALES" },
	{ code: 316, description: "PETRONAS" },
	{ code: 27, description: "PUMA" },
	{ code: 8, description: "RAMA" },
	{ code: 22, description: "SAKURA" },
	{ code: 10, description: "TECNECO" },
	{ code: 5, description: "TOTAL" },
	{ code: 3, description: "VALVOLINE" },
	{ code: 4, description: "VARIOS (FILTROS)" },
	{ code: 19, description: "VARIOS (LUBRICANTES)" },
	{ code: 11, description: "WAGNER LOCKHEED" },
	{ code: 26, description: "WEGA" },
];
